Components/NavigationMenuViewComponent.cs
using Assignment5.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment5.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IBookRepository repository;

        // constructor
        public NavigationMenuViewComponent (IBookRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            // sets the selected category in the ViewBag
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            // returns the list of distinct categories to the NavigationMenu Default view
            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Views/Shared/BookSummary.cshtml
@model Book

<div>
    <div class="card" style="width: 28rem;">
        <div class="card-body bg-light">
            <h5 class="card-title text-light bg-dark p-2">@Model.BookTitle</h5>
            <h6 class="card-subtitle mb-2 text-muted">@Model.AuthorFirstName @Model.AuthorLastName</h6>
            <p class="card-text">Classification: @Model.Classification, Category: @Model.Category, ISBN: @Model.ISBN, Pages: @Model.Pages</p>
            <a href="#" class="card-link">@Model.Publisher</a>
            <button type="button" class="btn btn-secondary float-right">@Model.Price</button>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">Bookstore</span>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                    <vc:navigation-menu />
            </div>
            <div class="col-7">
                @RenderBody()
            </div>
            <div class="col">

            </div>
        </div>
    </div>
</body>
</html>